# from uuid import uuid4

from tracardi.domain.system_entity_mapping import SystemEntityPropertyToColumn
from tracardi.domain.system_entity_table_column import SystemEntityTableColumn

default_profile_table_columns = [
    SystemEntityTableColumn(
        id="e63f494d-9db2-4a8e-aedd-4b0a939e270f",
        database="tracardi",
        table="profile",
        column="id",
        type="string",
        default=None,
        nullable=False
    ),
    SystemEntityTableColumn(
        id="1a4d727d-dc24-450f-bbe8-c32a89c6719a",
        database="tracardi",
        table="profile",
        column="ids",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c779481e-299b-4333-b1ec-74e379b22684",
        database="tracardi",
        table="profile",
        column="metadata_time_insert",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a785bb0f-215d-4d93-8fab-007f8ec7ec58",
        database="tracardi",
        table="profile",
        column="metadata_time_create",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="124ecf3b-b30e-40a5-9e3f-a6cadf4dcb21",
        database="tracardi",
        table="profile",
        column="metadata_time_update",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="39a27a6c-82bd-4352-a623-2a65b0cdd4b0",
        database="tracardi",
        table="profile",
        column="operation_new",
        type="bool",
        default='False',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="27b5df99-84b6-43e5-a13c-9f57159c4f71",
        database="tracardi",
        table="profile",
        column="operation_update",
        type="bool",
        default='False',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="930a5e7c-1315-4c25-9e3a-e46fcdd034b5",
        database="tracardi",
        table="profile",
        column="stats_visits",
        type="integer",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c5d9acb2-f16c-4b64-b691-6a9cbf4f9f91",
        database="tracardi",
        table="profile",
        column="stats_views",
        type="integer",
        default='0',
        nullable=False
    ),
    SystemEntityTableColumn(
        id="1aac4e3a-59d6-4e48-8b86-efd36cfd0992",
        database="tracardi",
        table="profile",
        column="stats_counters",
        type="dict",
        default='{}',
        nullable=False
    ),
    SystemEntityTableColumn(
        id="7f2ef0ea-3543-47e6-93f4-41b47836bed6",
        database="tracardi",
        table="profile",
        column="traits",
        type="dict",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="84c52865-c268-4996-922d-09b8dea698d3",
        database="tracardi",
        table="profile",
        column="segments",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="631d7f8d-3e3e-4c6e-8ea4-c57ff851796a",
        database="tracardi",
        table="profile",
        column="interests",
        type="dict",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8ad98361-58a0-426c-b502-b0d88ba5a51d",
        database="tracardi",
        table="profile",
        column="consents",
        type="Dict[str, ConsentRevoke]",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="9ced8bb6-62db-4464-9e88-682b45169306",
        database="tracardi",
        table="profile",
        column="active",
        type="bool",
        default='True',
        nullable=False
    ),
    SystemEntityTableColumn(
        id="1f1376eb-9f93-405a-87bf-3802b995acc8",
        database="tracardi",
        table="profile",
        column="aux",
        type="dict",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="20467887-3027-4c77-9cf1-e33a001dcada",
        database="tracardi",
        table="profile",
        column="data_anonymous",
        type="bool",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="994cb5b7-08de-4159-8ee1-9b2f05afff02",
        database="tracardi",
        table="profile",
        column="data_pii_firstname",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="5cf6e8c5-9151-4dfd-ba11-0b36005d9f10",
        database="tracardi",
        table="profile",
        column="data_pii_lastname",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ceb3a38f-ebf6-49f6-9174-5583e3cbeffd",
        database="tracardi",
        table="profile",
        column="data_pii_display_name",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="fc05a5b4-966c-428c-af1f-27bee80bcdc0",
        database="tracardi",
        table="profile",
        column="data_pii_birthday",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="3c732205-beb3-449b-944e-dc8e2f3ec81c",
        database="tracardi",
        table="profile",
        column="data_pii_language_native",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="08dcf673-6869-4591-905f-2c92b8b72de7",
        database="tracardi",
        table="profile",
        column="data_pii_language_spoken",
        type="List[str]",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="49226863-5d4e-4b76-9cf0-8f468fb15466",
        database="tracardi",
        table="profile",
        column="data_pii_gender",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="52d2e3f8-58ed-4ff5-872c-6c40545e3f1f",
        database="tracardi",
        table="profile",
        column="data_pii_education_level",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="b003f89d-b1d5-46a6-b360-9d0c12c603b5",
        database="tracardi",
        table="profile",
        column="data_pii_civil_status",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="5b94bda6-a6ac-490c-afc1-895d92026140",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_height",
        type="float",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1f9e60e2-47c7-4ab4-a16a-1a32b6864c96",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_weight",
        type="float",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="0124a7e1-5d4b-426f-bd50-7a2facc5122d",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_shoe_number",
        type="float",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ca9dbcd4-7408-4cca-b229-b0de6732392a",
        database="tracardi",
        table="profile",
        column="data_contact_email_main",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="836b11ba-ee5e-4bd8-86af-f042b634f18b",
        database="tracardi",
        table="profile",
        column="data_contact_email_private",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8711a0b1-9cfd-4c25-b52d-54c9ab8d9bc6",
        database="tracardi",
        table="profile",
        column="data_contact_email_business",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="83f0e7d9-ab10-4d1f-bce5-7b1ec1bff3df",
        database="tracardi",
        table="profile",
        column="data_contact_phone_main",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="9e4b455d-b126-4fce-b2d0-880112ebc2ce",
        database="tracardi",
        table="profile",
        column="data_contact_phone_business",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="588a8477-5944-4ca3-908b-2b37b0d2a114",
        database="tracardi",
        table="profile",
        column="data_contact_phone_mobile",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="4dfe2cd2-e0f2-48bd-b978-17fbb95ed9fa",
        database="tracardi",
        table="profile",
        column="data_contact_phone_whatsapp",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="b8a68f9e-fa43-438b-94ba-481dba43366a",
        database="tracardi",
        table="profile",
        column="data_contact_app_whatsapp",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="9a6f7ec9-1c4a-4478-9bd1-30a588982fda",
        database="tracardi",
        table="profile",
        column="data_contact_app_discord",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="6ef9658d-ec45-45d3-b9d4-682f6aa7e198",
        database="tracardi",
        table="profile",
        column="data_contact_app_slack",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ca931c5e-d0f2-4bc4-afc4-a80e6ff4bab1",
        database="tracardi",
        table="profile",
        column="data_contact_app_twitter",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ec155c9a-07cc-45a5-98a4-15f973f16250",
        database="tracardi",
        table="profile",
        column="data_contact_app_telegram",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="93d37ca1-25d6-41d7-afc1-8ba61876e178",
        database="tracardi",
        table="profile",
        column="data_contact_app_wechat",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="310b570b-b793-4dcd-9399-8c50710a5ba4",
        database="tracardi",
        table="profile",
        column="data_contact_app_viber",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="99aa5aea-ee4f-498b-936e-b1ef77a0ac52",
        database="tracardi",
        table="profile",
        column="data_contact_app_signal",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="2c6c592b-e7c3-411c-a141-dba896fcf41c",
        database="tracardi",
        table="profile",
        column="data_contact_address_town",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="7bd11a47-94ac-4a8b-be7d-9974e6cd75ba",
        database="tracardi",
        table="profile",
        column="data_contact_address_county",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="91518bdc-4cf2-4c2d-bb6f-5a0e28781d82",
        database="tracardi",
        table="profile",
        column="data_contact_address_country",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8d55216d-ca66-43ef-a494-a68d456cfdb3",
        database="tracardi",
        table="profile",
        column="data_contact_address_postcode",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="942b46a6-43c5-4a26-9146-b1a0d43115d6",
        database="tracardi",
        table="profile",
        column="data_contact_address_street",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="cf6f2082-c64c-425c-a10b-8626fc4d13ab",
        database="tracardi",
        table="profile",
        column="data_contact_address_other",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="95052724-279c-457c-8cc0-040aa2090168",
        database="tracardi",
        table="profile",
        column="data_identifier_id",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="2c8d058a-7cb3-431b-95dd-ca5f59ae551a",
        database="tracardi",
        table="profile",
        column="data_identifier_pk",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="373f0c1d-9fec-429e-8407-658cdd60489d",
        database="tracardi",
        table="profile",
        column="data_identifier_badge",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="cfa5d1aa-a3de-4173-ae93-9170ba360837",
        database="tracardi",
        table="profile",
        column="data_identifier_passport",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c802fe96-2934-418d-933b-423a9d98dee4",
        database="tracardi",
        table="profile",
        column="data_identifier_credit_card",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="509827be-2ff8-43a0-b19c-842726abc437",
        database="tracardi",
        table="profile",
        column="data_identifier_token",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="014c7fe9-127d-47ba-9a0a-70fcf110f65d",
        database="tracardi",
        table="profile",
        column="data_identifier_coupons",
        type="List[str]",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="10aed8f8-6bff-4984-93c6-2930b1e39676",
        database="tracardi",
        table="profile",
        column="data_media_image",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="5fe42722-6196-4706-a0a5-2c45269fe77d",
        database="tracardi",
        table="profile",
        column="data_media_webpage",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a66df419-2cfe-4178-a9db-7256856f28d1",
        database="tracardi",
        table="profile",
        column="data_media_social_twitter",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="503c7b63-1692-49f3-80ba-e4a0159f5c03",
        database="tracardi",
        table="profile",
        column="data_media_social_facebook",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1706071d-ed88-4681-87f5-dfc01aac96d3",
        database="tracardi",
        table="profile",
        column="data_media_social_youtube",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="d1c05ad6-db6c-4fb2-a23d-692e40884218",
        database="tracardi",
        table="profile",
        column="data_media_social_instagram",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="82428273-765c-4b34-ab47-5e4844018f0a",
        database="tracardi",
        table="profile",
        column="data_media_social_tiktok",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="e03b6a50-8ffc-4ba0-9dde-1492080abbb9",
        database="tracardi",
        table="profile",
        column="data_media_social_linkedin",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="9afb81cd-ef4e-4541-ac74-8669f2a66206",
        database="tracardi",
        table="profile",
        column="data_media_social_reddit",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c830e497-3feb-4de6-8209-a204706d7dcc",
        database="tracardi",
        table="profile",
        column="data_media_social_other",
        type="dict",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1bd081aa-c046-430a-b66e-896277107ac3",
        database="tracardi",
        table="profile",
        column="data_preferences_purchases",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="909cef70-7e09-4abc-87ad-50683ff3e2a1",
        database="tracardi",
        table="profile",
        column="data_preferences_colors",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="cccfe951-2c04-4a0e-9f9d-fe332f54eb5f",
        database="tracardi",
        table="profile",
        column="data_preferences_sizes",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="eeeceb92-6fe4-4cd0-b602-39a52860923c",
        database="tracardi",
        table="profile",
        column="data_preferences_devices",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="b86968fd-9f05-4c03-bab9-71f2948be896",
        database="tracardi",
        table="profile",
        column="data_preferences_channels",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c3036ef6-7b06-42d8-982f-b4dcb1c6dbf8",
        database="tracardi",
        table="profile",
        column="data_preferences_payments",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a032bf17-130a-447b-b846-839850fe653e",
        database="tracardi",
        table="profile",
        column="data_preferences_brands",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="f9b59277-9bf5-42e7-a8b0-d9e2767aedbf",
        database="tracardi",
        table="profile",
        column="data_preferences_fragrances",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="3f6624db-8481-4ed8-994a-ce75f1b0e291",
        database="tracardi",
        table="profile",
        column="data_preferences_services",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="0d0adda4-8cf6-4f92-80cc-baceb91a7112",
        database="tracardi",
        table="profile",
        column="data_preferences_other",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="635660c2-4fcb-41e6-8b14-42cb6c4e8615",
        database="tracardi",
        table="profile",
        column="data_job_position",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="f8550a44-cb59-4655-af1c-651675acd6ec",
        database="tracardi",
        table="profile",
        column="data_job_salary",
        type="float",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="d053d676-96b4-4152-8579-cc071a6e197b",
        database="tracardi",
        table="profile",
        column="data_job_type",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="aa33bded-78b9-4c2a-94fd-ee8665d6ba10",
        database="tracardi",
        table="profile",
        column="data_job_company_name",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="362c3f69-ad22-4c72-aa7c-b42fe52e9820",
        database="tracardi",
        table="profile",
        column="data_job_company_size",
        type="int",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1df26195-e779-44bd-8848-76db6fc7dceb",
        database="tracardi",
        table="profile",
        column="data_job_company_segment",
        type="List[str]",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c6feb282-5d63-477e-bae9-abb0fa25b96a",
        database="tracardi",
        table="profile",
        column="data_job_company_country",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="864090dc-e468-409d-ae99-38e9a54c1b92",
        database="tracardi",
        table="profile",
        column="data_job_department",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="e5b643a5-4d0b-4615-b6a1-b0b4f0ca0cb5",
        database="tracardi",
        table="profile",
        column="data_metrics_ltv",
        type="float",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a259b1a2-9bf6-4222-8da0-76a6d86aaf66",
        database="tracardi",
        table="profile",
        column="data_loyalty_codes",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a5baab99-e867-4d0f-91fd-3bc190e10dd2",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_id",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="e7dc4c68-9414-4354-b896-c8edd943cd5d",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_name",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="34c6c658-2dc7-496b-9a22-cb30df46a93d",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_issuer",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ab760f80-6e32-4012-918a-774337196380",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_expires",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="73206a75-edd6-442d-9a58-cfbfcdc0da6a",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_points",
        type="float",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="6fca8ab4-2471-40df-a12c-6c888a6918df",
        database="tracardi",
        table="profile",
        column="data_devices_push",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="bd1a3fb1-34aa-447a-8df6-b64c60171e8f",
        database="tracardi",
        table="profile",
        column="data_devices_other",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="be8fb25a-9439-41c8-8b0b-36ead967bc76",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_location",
        type="Tuple[float,float]",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="74e8e3a6-40cf-46d9-907f-a7e65d9b43e3",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_longitude",
        type="float",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="cfeff116-cabf-4ff4-9327-15ae3ef67602",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_latitude",
        type="float",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="dcf3d7a6-787e-45bb-8f25-2fa5abf55ec7",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_postal",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="d5419a86-fd9a-41b1-8311-0a5799e240cb",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_county",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1057c47a-fa1c-4588-a663-9db0a0f91346",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_city",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="331790a5-b0c6-4fae-a796-72e1dc1b70eb",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_country_code",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a1cdb1d0-c7e3-4023-83ce-8069e6b46569",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_country_name",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="13a3dffe-22d1-4d3a-886d-fb5244a5bfe9",
        database="tracardi",
        table="profile",
        column="data_contact_confirmations",
        type="List[str]",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="08f2dd31-6e45-4ca8-9dce-2b51d34a1472",
        database="tracardi",
        table="profile",
        column="stats_views",
        type="integer",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="faff3342-c074-4ffe-8ce9-f5ae32547ea1",
        database="tracardi",
        table="profile",
        column="stats_visits",
        type="integer",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8a9fcaee-de53-4a1d-9f4d-485e4df0a204",
        database="tracardi",
        table="profile",
        column="operation_merge",
        type="List[str]",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="39a9940b-ec54-4552-b7d2-58880af24b12",
        database="tracardi",
        table="profile",
        column="operation_segment",
        type="bool",
        default='false',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="540d0ed5-8ea0-4595-a998-5757479455d5",
        database="tracardi",
        table="profile",
        column="metadata_status",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="b27bc369-f1c3-43c6-977e-c4f01656ab77",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_tz",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8e3e72e3-6060-4b53-bc90-2eeeacd039e8",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_count",
        type="integer",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c98a3e81-9caa-469f-ad40-27bd98d0116f",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_current",
        type="datetime",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="739f575d-fdbc-4b28-99af-2aa9ee640f3a",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_last",
        type="datetime",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="fbd4f752-8deb-425a-9a35-331c9fb2b7eb",
        database="tracardi",
        table="profile",
        column="metadata_time_segmentation",
        type="datetime",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="78c40875-cb02-4814-80dd-b662a1922c62",
        database="tracardi",
        table="profile",
        column="primary_id",
        type="string",
        default='NULL',
        nullable=True
    ),
]

profile_properties_to_column_mapping = [
    SystemEntityPropertyToColumn(
        id="9b4febf8-3520-4855-827d-348821720094",
        database="tracardi",
        table="profile",
        column="id",
        entity="profile",
        property="id"
    ),
    SystemEntityPropertyToColumn(
        id="cdec20df-550a-40a2-9b29-0c918b5e63b8",
        database="tracardi",
        table="profile",
        column="ids",
        entity="profile",
        property="ids"
    ),
    SystemEntityPropertyToColumn(
        id="45f3e540-57d4-47c4-9484-2ee4195b331f",
        database="tracardi",
        table="profile",
        column="metadata_time_insert",
        entity="profile",
        property="metadata.time.insert"
    ),
    SystemEntityPropertyToColumn(
        id="480fd621-a495-4412-a350-011c8603ee66",
        database="tracardi",
        table="profile",
        column="metadata_time_create",
        entity="profile",
        property="metadata.time.create"
    ),
    SystemEntityPropertyToColumn(
        id="a818951f-369a-434d-b545-1d0a2fadfc0c",
        database="tracardi",
        table="profile",
        column="metadata_time_update",
        entity="profile",
        property="metadata.time.update"
    ),
    SystemEntityPropertyToColumn(
        id="9a294133-1af5-40ba-b275-817cc3614df7",
        database="tracardi",
        table="profile",
        column="operation_new",
        entity="profile",
        property="operation.new"
    ),
    SystemEntityPropertyToColumn(
        id="bc5e22ed-7b72-4aa8-bac8-704d4817e128",
        database="tracardi",
        table="profile",
        column="operation_update",
        entity="profile",
        property="operation.update"
    ),
    SystemEntityPropertyToColumn(
        id="39af336e-780b-437f-8ce2-ae7c3d2747c0",
        database="tracardi",
        table="profile",
        column="stats_visits",
        entity="profile",
        property="stats.visits"
    ),
    SystemEntityPropertyToColumn(
        id="95b8d1ae-f886-4f53-8d28-1974b2695365",
        database="tracardi",
        table="profile",
        column="stats_views",
        entity="profile",
        property="stats.views"
    ),
    SystemEntityPropertyToColumn(
        id="6bb77f13-c830-4eee-89c2-6c43d8f8930a",
        database="tracardi",
        table="profile",
        column="stats_counters",
        entity="profile",
        property="stats.counters"
    ),
    SystemEntityPropertyToColumn(
        id="a1c69cc6-ab26-4363-ba2f-94cf2f5c90e2",
        database="tracardi",
        table="profile",
        column="traits",
        entity="profile",
        property="traits"
    ),
    SystemEntityPropertyToColumn(
        id="e6ba5c71-7463-423c-a994-a77b551ecdac",
        database="tracardi",
        table="profile",
        column="segments",
        entity="profile",
        property="segments"
    ),
    SystemEntityPropertyToColumn(
        id="c2dbc3ce-23d5-497a-9e0c-1a0df7ba94ec",
        database="tracardi",
        table="profile",
        column="interests",
        entity="profile",
        property="interests"
    ),
    SystemEntityPropertyToColumn(
        id="28156104-2b1e-4bd8-8161-a4f49d78e459",
        database="tracardi",
        table="profile",
        column="consents",
        entity="profile",
        property="consents"
    ),
    SystemEntityPropertyToColumn(
        id="cec4b047-8f24-4ce8-beb4-b43f6f6ba968",
        database="tracardi",
        table="profile",
        column="active",
        entity="profile",
        property="active"
    ),
    SystemEntityPropertyToColumn(
        id="fcd85d6e-e7a7-49b3-a2ed-bc5de91e1938",
        database="tracardi",
        table="profile",
        column="aux",
        entity="profile",
        property="aux"
    ),
    SystemEntityPropertyToColumn(
        id="97df74fe-6d54-428d-936e-1c42a95a3784",
        database="tracardi",
        table="profile",
        column="data_anonymous",
        entity="profile",
        property="data.anonymous"
    ),
    SystemEntityPropertyToColumn(
        id="54cd819e-536c-4506-b691-a852a53f611a",
        database="tracardi",
        table="profile",
        column="data_pii_firstname",
        entity="profile",
        property="data.pii.firstname"
    ),
    SystemEntityPropertyToColumn(
        id="9d85e281-a0a8-4a19-82af-9f5f0aacae49",
        database="tracardi",
        table="profile",
        column="data_pii_lastname",
        entity="profile",
        property="data.pii.lastname"
    ),
    SystemEntityPropertyToColumn(
        id="9c767b2c-9b96-44b3-9f58-25894052a9b9",
        database="tracardi",
        table="profile",
        column="data_pii_display_name",
        entity="profile",
        property="data.pii.display_name"
    ),
    SystemEntityPropertyToColumn(
        id="a0f17dc6-768f-4a21-9ddf-dfa34ce0edca",
        database="tracardi",
        table="profile",
        column="data_pii_birthday",
        entity="profile",
        property="data.pii.birthday"
    ),
    SystemEntityPropertyToColumn(
        id="e9ee94f0-c28b-4df3-83c2-79ac22ab7e88",
        database="tracardi",
        table="profile",
        column="data_pii_language_native",
        entity="profile",
        property="data.pii.language.native"
    ),
    SystemEntityPropertyToColumn(
        id="47ef5bef-9fe7-4d3a-8ccf-8b1c322e1dcc",
        database="tracardi",
        table="profile",
        column="data_pii_language_spoken",
        entity="profile",
        property="data.pii.language.spoken"
    ),
    SystemEntityPropertyToColumn(
        id="429ad27d-b8ae-4bc2-8dfc-7ef8b435bd9d",
        database="tracardi",
        table="profile",
        column="data_pii_gender",
        entity="profile",
        property="data.pii.gender"
    ),
    SystemEntityPropertyToColumn(
        id="12741109-82cb-46a8-a1ab-b3b723791fab",
        database="tracardi",
        table="profile",
        column="data_pii_education_level",
        entity="profile",
        property="data.pii.education.level"
    ),
    SystemEntityPropertyToColumn(
        id="cd96d593-0b65-4c5c-bf90-3208264e6b50",
        database="tracardi",
        table="profile",
        column="data_pii_civil_status",
        entity="profile",
        property="data.pii.civil.status"
    ),
    SystemEntityPropertyToColumn(
        id="9de42d3e-b119-4bd3-8695-583d2a6386a4",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_height",
        entity="profile",
        property="data.pii.attributes.height"
    ),
    SystemEntityPropertyToColumn(
        id="e73f5dd5-1c15-4fc8-8574-ee2078496740",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_weight",
        entity="profile",
        property="data.pii.attributes.weight"
    ),
    SystemEntityPropertyToColumn(
        id="a570f00f-a0ac-443a-baec-6d9273303889",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_shoe_number",
        entity="profile",
        property="data.pii.attributes.shoe_number"
    ),
    SystemEntityPropertyToColumn(
        id="c4678cd6-af07-415b-b9bb-6012ebbad372",
        database="tracardi",
        table="profile",
        column="data_contact_email_main",
        entity="profile",
        property="data.contact.email.main"
    ),
    SystemEntityPropertyToColumn(
        id="f23d9900-3c26-435b-808c-8386ad200a2b",
        database="tracardi",
        table="profile",
        column="data_contact_email_private",
        entity="profile",
        property="data.contact.email.private"
    ),
    SystemEntityPropertyToColumn(
        id="6ff32e2d-00fb-43fa-b139-8e98a3febb08",
        database="tracardi",
        table="profile",
        column="data_contact_email_business",
        entity="profile",
        property="data.contact.email.business"
    ),
    SystemEntityPropertyToColumn(
        id="dbfdbb81-18b6-41a3-93b6-c1fa42723276",
        database="tracardi",
        table="profile",
        column="data_contact_phone_main",
        entity="profile",
        property="data.contact.phone.main"
    ),
    SystemEntityPropertyToColumn(
        id="d9d0ad91-9047-40c1-8d3a-8dc1269e63ab",
        database="tracardi",
        table="profile",
        column="data_contact_phone_business",
        entity="profile",
        property="data.contact.phone.business"
    ),
    SystemEntityPropertyToColumn(
        id="99037c75-09c5-47e2-8be1-f67404097311",
        database="tracardi",
        table="profile",
        column="data_contact_phone_mobile",
        entity="profile",
        property="data.contact.phone.mobile"
    ),
    SystemEntityPropertyToColumn(
        id="1b902fa1-b845-4b95-8bd6-2604b5bed952",
        database="tracardi",
        table="profile",
        column="data_contact_phone_whatsapp",
        entity="profile",
        property="data.contact.phone.whatsapp"
    ),
    SystemEntityPropertyToColumn(
        id="cfd8d2f7-59b8-4a7d-84bb-c1761ef90f93",
        database="tracardi",
        table="profile",
        column="data_contact_app_whatsapp",
        entity="profile",
        property="data.contact.app.whatsapp"
    ),
    SystemEntityPropertyToColumn(
        id="23999698-6a5b-4101-ba5e-9b1220c004b0",
        database="tracardi",
        table="profile",
        column="data_contact_app_discord",
        entity="profile",
        property="data.contact.app.discord"
    ),
    SystemEntityPropertyToColumn(
        id="1db6885f-004a-41a8-b51e-6dd4d6a88d78",
        database="tracardi",
        table="profile",
        column="data_contact_app_slack",
        entity="profile",
        property="data.contact.app.slack"
    ),
    SystemEntityPropertyToColumn(
        id="20178960-e99c-42c5-8f80-29cd06393b0d",
        database="tracardi",
        table="profile",
        column="data_contact_app_twitter",
        entity="profile",
        property="data.contact.app.twitter"
    ),
    SystemEntityPropertyToColumn(
        id="17ab4549-9b87-4e12-8625-ded290618626",
        database="tracardi",
        table="profile",
        column="data_contact_app_telegram",
        entity="profile",
        property="data.contact.app.telegram"
    ),
    SystemEntityPropertyToColumn(
        id="0ee7ecd8-5b82-4687-88b3-3b471f5328dc",
        database="tracardi",
        table="profile",
        column="data_contact_app_wechat",
        entity="profile",
        property="data.contact.app.wechat"
    ),
    SystemEntityPropertyToColumn(
        id="056f1cf7-83e9-4dad-94eb-ca8e75e96610",
        database="tracardi",
        table="profile",
        column="data_contact_app_viber",
        entity="profile",
        property="data.contact.app.viber"
    ),
    SystemEntityPropertyToColumn(
        id="d39adf1b-5147-43d8-aa78-c9e249de7ea2",
        database="tracardi",
        table="profile",
        column="data_contact_app_signal",
        entity="profile",
        property="data.contact.app.signal"
    ),
    SystemEntityPropertyToColumn(
        id="0947350e-19bb-4a00-ac21-b9a37033b783",
        database="tracardi",
        table="profile",
        column="data_contact_address_town",
        entity="profile",
        property="data.contact.address.town"
    ),
    SystemEntityPropertyToColumn(
        id="0e0714db-75a9-4017-86ae-393dd3e062ce",
        database="tracardi",
        table="profile",
        column="data_contact_address_county",
        entity="profile",
        property="data.contact.address.county"
    ),
    SystemEntityPropertyToColumn(
        id="b2ec7e0b-b4f6-4642-ab77-9ac012cb35c8",
        database="tracardi",
        table="profile",
        column="data_contact_address_country",
        entity="profile",
        property="data.contact.address.country"
    ),
    SystemEntityPropertyToColumn(
        id="dd8068aa-18e8-4cbd-ac30-49859a2a46d4",
        database="tracardi",
        table="profile",
        column="data_contact_address_postcode",
        entity="profile",
        property="data.contact.address.postcode"
    ),
    SystemEntityPropertyToColumn(
        id="7bb33c82-0c11-4527-84d0-3f7642be79a1",
        database="tracardi",
        table="profile",
        column="data_contact_address_street",
        entity="profile",
        property="data.contact.address.street"
    ),
    SystemEntityPropertyToColumn(
        id="165586f8-f3b8-4122-95d8-32894fbd5a34",
        database="tracardi",
        table="profile",
        column="data_contact_address_other",
        entity="profile",
        property="data.contact.address.other"
    ),
    SystemEntityPropertyToColumn(
        id="b50dcb2a-9805-484e-809f-be4604369535",
        database="tracardi",
        table="profile",
        column="data_identifier_id",
        entity="profile",
        property="data.identifier.id"
    ),
    SystemEntityPropertyToColumn(
        id="6ce94846-13b0-41f2-a4f9-32d162659496",
        database="tracardi",
        table="profile",
        column="data_identifier_pk",
        entity="profile",
        property="data.identifier.pk"
    ),
    SystemEntityPropertyToColumn(
        id="0ff2d57c-bd77-48d4-8bd0-8d69a5d66eb5",
        database="tracardi",
        table="profile",
        column="data_identifier_badge",
        entity="profile",
        property="data.identifier.badge"
    ),
    SystemEntityPropertyToColumn(
        id="b5eb3710-e7e6-4add-aa70-9a80adced5cf",
        database="tracardi",
        table="profile",
        column="data_identifier_passport",
        entity="profile",
        property="data.identifier.passport"
    ),
    SystemEntityPropertyToColumn(
        id="11765b81-d996-45c4-ad04-1e617dc8f057",
        database="tracardi",
        table="profile",
        column="data_identifier_credit_card",
        entity="profile",
        property="data.identifier.credit_card"
    ),
    SystemEntityPropertyToColumn(
        id="b5d81e29-0ad9-48a3-8a8b-e2e5fbf97a04",
        database="tracardi",
        table="profile",
        column="data_identifier_token",
        entity="profile",
        property="data.identifier.token"
    ),
    SystemEntityPropertyToColumn(
        id="41e5b14b-7042-4292-a91a-71f19e0e487e",
        database="tracardi",
        table="profile",
        column="data_identifier_coupons",
        entity="profile",
        property="data.identifier.coupons"
    ),
    SystemEntityPropertyToColumn(
        id="4aaf3899-6ded-49fc-9451-a4acff316cf1",
        database="tracardi",
        table="profile",
        column="data_media_image",
        entity="profile",
        property="data.media.image"
    ),
    SystemEntityPropertyToColumn(
        id="9ddce442-ddc0-462b-851c-750ae5924c0c",
        database="tracardi",
        table="profile",
        column="data_media_webpage",
        entity="profile",
        property="data.media.webpage"
    ),
    SystemEntityPropertyToColumn(
        id="f755bf59-95de-4971-9e9d-ac938c7ba5e3",
        database="tracardi",
        table="profile",
        column="data_media_social_twitter",
        entity="profile",
        property="data.media.social.twitter"
    ),
    SystemEntityPropertyToColumn(
        id="a1e10153-2c93-409c-a5f2-3683fd6a5dba",
        database="tracardi",
        table="profile",
        column="data_media_social_facebook",
        entity="profile",
        property="data.media.social.facebook"
    ),
    SystemEntityPropertyToColumn(
        id="7d868a1f-2910-4c9a-8ef6-5860e6d6b989",
        database="tracardi",
        table="profile",
        column="data_media_social_youtube",
        entity="profile",
        property="data.media.social.youtube"
    ),
    SystemEntityPropertyToColumn(
        id="332f40b4-1a74-4e5c-af21-224d0721056d",
        database="tracardi",
        table="profile",
        column="data_media_social_instagram",
        entity="profile",
        property="data.media.social.instagram"
    ),
    SystemEntityPropertyToColumn(
        id="80a75fcc-bbb7-4f38-8cde-8e451ffe7920",
        database="tracardi",
        table="profile",
        column="data_media_social_tiktok",
        entity="profile",
        property="data.media.social.tiktok"
    ),
    SystemEntityPropertyToColumn(
        id="8178a32a-9829-488d-85f5-5382e8325a22",
        database="tracardi",
        table="profile",
        column="data_media_social_linkedin",
        entity="profile",
        property="data.media.social.linkedin"
    ),
    SystemEntityPropertyToColumn(
        id="a0407243-b171-4a5c-b03d-382e035a679f",
        database="tracardi",
        table="profile",
        column="data_media_social_reddit",
        entity="profile",
        property="data.media.social.reddit"
    ),
    SystemEntityPropertyToColumn(
        id="bf8be29d-1056-4927-91c3-3b0820449f95",
        database="tracardi",
        table="profile",
        column="data_media_social_other",
        entity="profile",
        property="data.media.social.other"
    ),
    SystemEntityPropertyToColumn(
        id="d05a559c-fef7-47ee-90e3-9dc8b31d4db1",
        database="tracardi",
        table="profile",
        column="data_preferences_purchases",
        entity="profile",
        property="data.preferences.purchases"
    ),
    SystemEntityPropertyToColumn(
        id="042c3a8e-05b0-494f-9e4b-64c8eb167de2",
        database="tracardi",
        table="profile",
        column="data_preferences_colors",
        entity="profile",
        property="data.preferences.colors"
    ),
    SystemEntityPropertyToColumn(
        id="8240be64-b912-400d-84f8-aa8ed564ff63",
        database="tracardi",
        table="profile",
        column="data_preferences_sizes",
        entity="profile",
        property="data.preferences.sizes"
    ),
    SystemEntityPropertyToColumn(
        id="fd99e93f-fdd2-468a-bb73-272919333d76",
        database="tracardi",
        table="profile",
        column="data_preferences_devices",
        entity="profile",
        property="data.preferences.devices"
    ),
    SystemEntityPropertyToColumn(
        id="3a49fe7c-5c80-465a-8cf9-27bfd9ee0330",
        database="tracardi",
        table="profile",
        column="data_preferences_channels",
        entity="profile",
        property="data.preferences.channels"
    ),
    SystemEntityPropertyToColumn(
        id="f8d6423b-31d1-4aba-815d-a3b8b10a4cc8",
        database="tracardi",
        table="profile",
        column="data_preferences_payments",
        entity="profile",
        property="data.preferences.payments"
    ),
    SystemEntityPropertyToColumn(
        id="c79adc2a-bfb8-4f06-9a15-a0824b81e78b",
        database="tracardi",
        table="profile",
        column="data_preferences_brands",
        entity="profile",
        property="data.preferences.brands"
    ),
    SystemEntityPropertyToColumn(
        id="b70d6c80-0841-4006-aad3-b63fbab47492",
        database="tracardi",
        table="profile",
        column="data_preferences_fragrances",
        entity="profile",
        property="data.preferences.fragrances"
    ),
    SystemEntityPropertyToColumn(
        id="7149fa85-7056-4685-93a2-e5fc845fee09",
        database="tracardi",
        table="profile",
        column="data_preferences_services",
        entity="profile",
        property="data.preferences.services"
    ),
    SystemEntityPropertyToColumn(
        id="d275a8e2-8d25-4759-8f2a-adf7013f4f88",
        database="tracardi",
        table="profile",
        column="data_preferences_other",
        entity="profile",
        property="data.preferences.other"
    ),
    SystemEntityPropertyToColumn(
        id="610eadbd-727e-431d-a09d-c414a7a2ba29",
        database="tracardi",
        table="profile",
        column="data_job_position",
        entity="profile",
        property="data.job.position"
    ),
    SystemEntityPropertyToColumn(
        id="4d12689f-9e04-471d-ab1e-646e262341fc",
        database="tracardi",
        table="profile",
        column="data_job_salary",
        entity="profile",
        property="data.job.salary"
    ),
    SystemEntityPropertyToColumn(
        id="0f61e406-6b80-4123-8bf4-ca952b7c1a02",
        database="tracardi",
        table="profile",
        column="data_job_type",
        entity="profile",
        property="data.job.type"
    ),
    SystemEntityPropertyToColumn(
        id="eb8d96fa-a4f1-45cb-aa54-3b7c7622bc2e",
        database="tracardi",
        table="profile",
        column="data_job_company_name",
        entity="profile",
        property="data.job.company.name"
    ),
    SystemEntityPropertyToColumn(
        id="2f63d9d9-ea83-4ed1-9f6e-ff5642d769b7",
        database="tracardi",
        table="profile",
        column="data_job_company_size",
        entity="profile",
        property="data.job.company.size"
    ),
    SystemEntityPropertyToColumn(
        id="6e848d70-7ac5-4e96-83fe-0bac97265d19",
        database="tracardi",
        table="profile",
        column="data_job_company_segment",
        entity="profile",
        property="data.job.company.segment"
    ),
    SystemEntityPropertyToColumn(
        id="4729abda-f2ac-4274-80d7-134ca1dd0925",
        database="tracardi",
        table="profile",
        column="data_job_company_country",
        entity="profile",
        property="data.job.company.country"
    ),
    SystemEntityPropertyToColumn(
        id="08c71f9a-c890-4c36-9bcf-0f7ab0fac055",
        database="tracardi",
        table="profile",
        column="data_job_department",
        entity="profile",
        property="data.job.department"
    ),
    SystemEntityPropertyToColumn(
        id="21eb1c2e-111f-4cae-86e4-53a5932bfa2e",
        database="tracardi",
        table="profile",
        column="data_metrics_ltv",
        entity="profile",
        property="data.metrics.ltv"
    ),
    SystemEntityPropertyToColumn(
        id="577ba701-5214-4365-a490-6bf7e6257ea4",
        database="tracardi",
        table="profile",
        column="data_loyalty_codes",
        entity="profile",
        property="data.loyalty.codes"
    ),
    SystemEntityPropertyToColumn(
        id="15621a4c-565d-4043-9287-aba2a9a6bfad",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_id",
        entity="profile",
        property="data.loyalty.card.id"
    ),
    SystemEntityPropertyToColumn(
        id="79ec5f0a-67bd-4737-9f39-df899f2c66b6",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_name",
        entity="profile",
        property="data.loyalty.card.name"
    ),
    SystemEntityPropertyToColumn(
        id="7e31629b-e6c6-425f-a138-a380b40dc6b2",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_issuer",
        entity="profile",
        property="data.loyalty.card.issuer"
    ),
    SystemEntityPropertyToColumn(
        id="99d06b41-da52-48b8-8030-039ea4ba701e",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_expires",
        entity="profile",
        property="data.loyalty.card.expires"
    ),
    SystemEntityPropertyToColumn(
        id="d8aa137e-f10a-4f73-a923-0189918ad1e1",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_points",
        entity="profile",
        property="data.loyalty.card.points"
    ),
    SystemEntityPropertyToColumn(
        id="81ada287-1bab-4aa0-9c3b-9c18dd8b1a59",
        database="tracardi",
        table="profile",
        column="data_devices_push",
        entity="profile",
        property="data.devices.push"
    ),
    SystemEntityPropertyToColumn(
        id="a25301ca-f427-4381-945e-88ae3f1d53f3",
        database="tracardi",
        table="profile",
        column="data_devices_other",
        entity="profile",
        property="data.devices.other"
    ),
    SystemEntityPropertyToColumn(
        id="d2c9ec03-7bc3-4bbd-8e4d-8782a0156f67",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_location",
        entity="profile",
        property="data.devices.last.geo.location"
    ),
    SystemEntityPropertyToColumn(
        id="f594d03b-d44b-4bb7-8281-3a1d65cb3f31",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_longitude",
        entity="profile",
        property="data.devices.last.geo.longitude"
    ),
    SystemEntityPropertyToColumn(
        id="6aa96580-5859-40e7-819f-19f2572f4788",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_latitude",
        entity="profile",
        property="data.devices.last.geo.latitude"
    ),
    SystemEntityPropertyToColumn(
        id="68d10f7a-60c2-4ed6-bb81-f2316d17fd32",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_postal",
        entity="profile",
        property="data.devices.last.geo.postal"
    ),
    SystemEntityPropertyToColumn(
        id="72fb5a3d-46f7-4c0b-9ff5-b56d1c6db2c9",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_county",
        entity="profile",
        property="data.devices.last.geo.county"
    ),
    SystemEntityPropertyToColumn(
        id="43d9fa35-cf9e-4fde-844c-4f4dd41c0266",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_city",
        entity="profile",
        property="data.devices.last.geo.city"
    ),
    SystemEntityPropertyToColumn(
        id="9cd630a2-d583-45d8-9ad1-6612519d54f4",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_country_code",
        entity="profile",
        property="data.devices.last.geo.country.code"
    ),
    SystemEntityPropertyToColumn(
        id="7ffd1bcd-93b7-4a63-b13d-433c05dbcccd",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_country_name",
        entity="profile",
        property="data.devices.last.geo.country.name"
    ),
    SystemEntityPropertyToColumn(
        id="0ffedd4a-72d4-4e85-9901-4a7635c75bd9",
        database="tracardi",
        table="profile",
        column="data_contact_confirmations",
        entity="profile",
        property="data.contact.confirmations"
    ),
    SystemEntityPropertyToColumn(
        id="8093dcff-ed58-4dd0-aafa-fabc27825d34",
        database="tracardi",
        table="profile",
        column="stats_views",
        entity="profile",
        property="stats.views"
    ),
    SystemEntityPropertyToColumn(
        id="72106f5e-f5de-4778-9bad-f922eb92aa72",
        database="tracardi",
        table="profile",
        column="stats_visits",
        entity="profile",
        property="stats.visits"
    ),
    SystemEntityPropertyToColumn(
        id="13f5148a-2c7a-48f1-92b7-333e2b65a02d",
        database="tracardi",
        table="profile",
        column="operation_merge",
        entity="profile",
        property="operation.merge"
    ),
    SystemEntityPropertyToColumn(
        id="596b1907-547e-45e6-99a9-8d3b50da727a",
        database="tracardi",
        table="profile",
        column="operation_segment",
        entity="profile",
        property="operation.segment"
    ),
    SystemEntityPropertyToColumn(
        id="cfaf3d5b-376e-49d6-9d93-d94ecce2b4e3",
        database="tracardi",
        table="profile",
        column="metadata_status",
        entity="profile",
        property="metadata.status"
    ),
    SystemEntityPropertyToColumn(
        id="54c4b88c-5b83-45d1-bc8b-d251d8118849",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_tz",
        entity="profile",
        property="metadata.time.visit.tz"
    ),
    SystemEntityPropertyToColumn(
        id="746665f4-5d0f-46bc-b5b1-58e6f1e22324",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_count",
        entity="profile",
        property="metadata.time.visit.count"
    ),
    SystemEntityPropertyToColumn(
        id="978701b2-c489-4ede-b1bb-9c6acbd153b1",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_current",
        entity="profile",
        property="metadata.time.visit.current"
    ),
    SystemEntityPropertyToColumn(
        id="1d1e9b1e-d7ea-4da9-b6ac-7f11e57de37c",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_last",
        entity="profile",
        property="metadata.time.visit.last"
    ),
    SystemEntityPropertyToColumn(
        id="a79e907c-24c3-4f9a-a605-39ccb9bf50ff",
        database="tracardi",
        table="profile",
        column="metadata_time_segmentation",
        entity="profile",
        property="metadata.time.segmentation"
    ),
    SystemEntityPropertyToColumn(
        id="e6786d5d-ff33-4fe5-8340-94d2cdf2fac2",
        database="tracardi",
        table="profile",
        column="primary_id",
        entity="profile",
        property="primary_id"
    )
]

# for x in default_profile_table_columns:
#     print(
# f"""SystemEntityTableColumn(
#     id = "{uuid4()}",
#     database = "{x.database}",
#     table = "{x.table}",
#     column = "{x.id}",
#     type = "{x.type}",
#     default = {f"'{x.default}'" if x.default is not None else None},
#     nullable = {x.nullable}
# ),"""
#     )
