from tracardi.domain.system_entity_table_column import SystemEntityTableColumn

default_profile_table_columns = [
    SystemEntityTableColumn(
        id="e63f494d-9db2-4a8e-aedd-4b0a939e270f",
        database="tracardi",
        table="profile",
        column="id",
        type="string",
        default=None,
        nullable=False
    ),
    SystemEntityTableColumn(
        id="1a4d727d-dc24-450f-bbe8-c32a89c6719a",
        database="tracardi",
        table="profile",
        column="ids",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c779481e-299b-4333-b1ec-74e379b22684",
        database="tracardi",
        table="profile",
        column="metadata_time_insert",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a785bb0f-215d-4d93-8fab-007f8ec7ec58",
        database="tracardi",
        table="profile",
        column="metadata_time_create",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="124ecf3b-b30e-40a5-9e3f-a6cadf4dcb21",
        database="tracardi",
        table="profile",
        column="metadata_time_update",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="39a27a6c-82bd-4352-a623-2a65b0cdd4b0",
        database="tracardi",
        table="profile",
        column="operation_new",
        type="bool",
        default='False',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="27b5df99-84b6-43e5-a13c-9f57159c4f71",
        database="tracardi",
        table="profile",
        column="operation_update",
        type="bool",
        default='False',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="930a5e7c-1315-4c25-9e3a-e46fcdd034b5",
        database="tracardi",
        table="profile",
        column="stats_visits",
        type="integer",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c5d9acb2-f16c-4b64-b691-6a9cbf4f9f91",
        database="tracardi",
        table="profile",
        column="stats_views",
        type="integer",
        default='0',
        nullable=False
    ),
    SystemEntityTableColumn(
        id="1aac4e3a-59d6-4e48-8b86-efd36cfd0992",
        database="tracardi",
        table="profile",
        column="stats_counters",
        type="dict",
        default='{}',
        nullable=False
    ),
    SystemEntityTableColumn(
        id="7f2ef0ea-3543-47e6-93f4-41b47836bed6",
        database="tracardi",
        table="profile",
        column="traits",
        type="dict",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="84c52865-c268-4996-922d-09b8dea698d3",
        database="tracardi",
        table="profile",
        column="segments",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="631d7f8d-3e3e-4c6e-8ea4-c57ff851796a",
        database="tracardi",
        table="profile",
        column="interests",
        type="dict",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8ad98361-58a0-426c-b502-b0d88ba5a51d",
        database="tracardi",
        table="profile",
        column="consents",
        type="Dict[str, ConsentRevoke]",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="9ced8bb6-62db-4464-9e88-682b45169306",
        database="tracardi",
        table="profile",
        column="active",
        type="bool",
        default='True',
        nullable=False
    ),
    SystemEntityTableColumn(
        id="1f1376eb-9f93-405a-87bf-3802b995acc8",
        database="tracardi",
        table="profile",
        column="aux",
        type="dict",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="20467887-3027-4c77-9cf1-e33a001dcada",
        database="tracardi",
        table="profile",
        column="data_anonymous",
        type="bool",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="994cb5b7-08de-4159-8ee1-9b2f05afff02",
        database="tracardi",
        table="profile",
        column="data_pii_firstname",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="5cf6e8c5-9151-4dfd-ba11-0b36005d9f10",
        database="tracardi",
        table="profile",
        column="data_pii_lastname",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ceb3a38f-ebf6-49f6-9174-5583e3cbeffd",
        database="tracardi",
        table="profile",
        column="data_pii_display_name",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="fc05a5b4-966c-428c-af1f-27bee80bcdc0",
        database="tracardi",
        table="profile",
        column="data_pii_birthday",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="3c732205-beb3-449b-944e-dc8e2f3ec81c",
        database="tracardi",
        table="profile",
        column="data_pii_language_native",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="08dcf673-6869-4591-905f-2c92b8b72de7",
        database="tracardi",
        table="profile",
        column="data_pii_language_spoken",
        type="List[str]",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="49226863-5d4e-4b76-9cf0-8f468fb15466",
        database="tracardi",
        table="profile",
        column="data_pii_gender",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="52d2e3f8-58ed-4ff5-872c-6c40545e3f1f",
        database="tracardi",
        table="profile",
        column="data_pii_education_level",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="b003f89d-b1d5-46a6-b360-9d0c12c603b5",
        database="tracardi",
        table="profile",
        column="data_pii_civil_status",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="5b94bda6-a6ac-490c-afc1-895d92026140",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_height",
        type="float",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1f9e60e2-47c7-4ab4-a16a-1a32b6864c96",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_weight",
        type="float",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="0124a7e1-5d4b-426f-bd50-7a2facc5122d",
        database="tracardi",
        table="profile",
        column="data_pii_attributes_shoe_number",
        type="float",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ca9dbcd4-7408-4cca-b229-b0de6732392a",
        database="tracardi",
        table="profile",
        column="data_contact_email_main",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="836b11ba-ee5e-4bd8-86af-f042b634f18b",
        database="tracardi",
        table="profile",
        column="data_contact_email_private",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8711a0b1-9cfd-4c25-b52d-54c9ab8d9bc6",
        database="tracardi",
        table="profile",
        column="data_contact_email_business",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="83f0e7d9-ab10-4d1f-bce5-7b1ec1bff3df",
        database="tracardi",
        table="profile",
        column="data_contact_phone_main",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="9e4b455d-b126-4fce-b2d0-880112ebc2ce",
        database="tracardi",
        table="profile",
        column="data_contact_phone_business",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="588a8477-5944-4ca3-908b-2b37b0d2a114",
        database="tracardi",
        table="profile",
        column="data_contact_phone_mobile",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="4dfe2cd2-e0f2-48bd-b978-17fbb95ed9fa",
        database="tracardi",
        table="profile",
        column="data_contact_phone_whatsapp",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="b8a68f9e-fa43-438b-94ba-481dba43366a",
        database="tracardi",
        table="profile",
        column="data_contact_app_whatsapp",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="9a6f7ec9-1c4a-4478-9bd1-30a588982fda",
        database="tracardi",
        table="profile",
        column="data_contact_app_discord",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="6ef9658d-ec45-45d3-b9d4-682f6aa7e198",
        database="tracardi",
        table="profile",
        column="data_contact_app_slack",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ca931c5e-d0f2-4bc4-afc4-a80e6ff4bab1",
        database="tracardi",
        table="profile",
        column="data_contact_app_twitter",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ec155c9a-07cc-45a5-98a4-15f973f16250",
        database="tracardi",
        table="profile",
        column="data_contact_app_telegram",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="93d37ca1-25d6-41d7-afc1-8ba61876e178",
        database="tracardi",
        table="profile",
        column="data_contact_app_wechat",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="310b570b-b793-4dcd-9399-8c50710a5ba4",
        database="tracardi",
        table="profile",
        column="data_contact_app_viber",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="99aa5aea-ee4f-498b-936e-b1ef77a0ac52",
        database="tracardi",
        table="profile",
        column="data_contact_app_signal",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="2c6c592b-e7c3-411c-a141-dba896fcf41c",
        database="tracardi",
        table="profile",
        column="data_contact_address_town",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="7bd11a47-94ac-4a8b-be7d-9974e6cd75ba",
        database="tracardi",
        table="profile",
        column="data_contact_address_county",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="91518bdc-4cf2-4c2d-bb6f-5a0e28781d82",
        database="tracardi",
        table="profile",
        column="data_contact_address_country",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8d55216d-ca66-43ef-a494-a68d456cfdb3",
        database="tracardi",
        table="profile",
        column="data_contact_address_postcode",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="942b46a6-43c5-4a26-9146-b1a0d43115d6",
        database="tracardi",
        table="profile",
        column="data_contact_address_street",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="cf6f2082-c64c-425c-a10b-8626fc4d13ab",
        database="tracardi",
        table="profile",
        column="data_contact_address_other",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="95052724-279c-457c-8cc0-040aa2090168",
        database="tracardi",
        table="profile",
        column="data_identifier_id",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="2c8d058a-7cb3-431b-95dd-ca5f59ae551a",
        database="tracardi",
        table="profile",
        column="data_identifier_pk",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="373f0c1d-9fec-429e-8407-658cdd60489d",
        database="tracardi",
        table="profile",
        column="data_identifier_badge",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="cfa5d1aa-a3de-4173-ae93-9170ba360837",
        database="tracardi",
        table="profile",
        column="data_identifier_passport",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c802fe96-2934-418d-933b-423a9d98dee4",
        database="tracardi",
        table="profile",
        column="data_identifier_credit_card",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="509827be-2ff8-43a0-b19c-842726abc437",
        database="tracardi",
        table="profile",
        column="data_identifier_token",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="014c7fe9-127d-47ba-9a0a-70fcf110f65d",
        database="tracardi",
        table="profile",
        column="data_identifier_coupons",
        type="List[str]",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="10aed8f8-6bff-4984-93c6-2930b1e39676",
        database="tracardi",
        table="profile",
        column="data_media_image",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="5fe42722-6196-4706-a0a5-2c45269fe77d",
        database="tracardi",
        table="profile",
        column="data_media_webpage",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a66df419-2cfe-4178-a9db-7256856f28d1",
        database="tracardi",
        table="profile",
        column="data_media_social_twitter",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="503c7b63-1692-49f3-80ba-e4a0159f5c03",
        database="tracardi",
        table="profile",
        column="data_media_social_facebook",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1706071d-ed88-4681-87f5-dfc01aac96d3",
        database="tracardi",
        table="profile",
        column="data_media_social_youtube",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="d1c05ad6-db6c-4fb2-a23d-692e40884218",
        database="tracardi",
        table="profile",
        column="data_media_social_instagram",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="82428273-765c-4b34-ab47-5e4844018f0a",
        database="tracardi",
        table="profile",
        column="data_media_social_tiktok",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="e03b6a50-8ffc-4ba0-9dde-1492080abbb9",
        database="tracardi",
        table="profile",
        column="data_media_social_linkedin",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="9afb81cd-ef4e-4541-ac74-8669f2a66206",
        database="tracardi",
        table="profile",
        column="data_media_social_reddit",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c830e497-3feb-4de6-8209-a204706d7dcc",
        database="tracardi",
        table="profile",
        column="data_media_social_other",
        type="dict",
        default='{}',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1bd081aa-c046-430a-b66e-896277107ac3",
        database="tracardi",
        table="profile",
        column="data_preferences_purchases",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="909cef70-7e09-4abc-87ad-50683ff3e2a1",
        database="tracardi",
        table="profile",
        column="data_preferences_colors",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="cccfe951-2c04-4a0e-9f9d-fe332f54eb5f",
        database="tracardi",
        table="profile",
        column="data_preferences_sizes",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="eeeceb92-6fe4-4cd0-b602-39a52860923c",
        database="tracardi",
        table="profile",
        column="data_preferences_devices",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="b86968fd-9f05-4c03-bab9-71f2948be896",
        database="tracardi",
        table="profile",
        column="data_preferences_channels",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c3036ef6-7b06-42d8-982f-b4dcb1c6dbf8",
        database="tracardi",
        table="profile",
        column="data_preferences_payments",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a032bf17-130a-447b-b846-839850fe653e",
        database="tracardi",
        table="profile",
        column="data_preferences_brands",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="f9b59277-9bf5-42e7-a8b0-d9e2767aedbf",
        database="tracardi",
        table="profile",
        column="data_preferences_fragrances",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="3f6624db-8481-4ed8-994a-ce75f1b0e291",
        database="tracardi",
        table="profile",
        column="data_preferences_services",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="0d0adda4-8cf6-4f92-80cc-baceb91a7112",
        database="tracardi",
        table="profile",
        column="data_preferences_other",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="635660c2-4fcb-41e6-8b14-42cb6c4e8615",
        database="tracardi",
        table="profile",
        column="data_job_position",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="f8550a44-cb59-4655-af1c-651675acd6ec",
        database="tracardi",
        table="profile",
        column="data_job_salary",
        type="float",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="d053d676-96b4-4152-8579-cc071a6e197b",
        database="tracardi",
        table="profile",
        column="data_job_type",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="aa33bded-78b9-4c2a-94fd-ee8665d6ba10",
        database="tracardi",
        table="profile",
        column="data_job_company_name",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="362c3f69-ad22-4c72-aa7c-b42fe52e9820",
        database="tracardi",
        table="profile",
        column="data_job_company_size",
        type="int",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1df26195-e779-44bd-8848-76db6fc7dceb",
        database="tracardi",
        table="profile",
        column="data_job_company_segment",
        type="List[str]",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c6feb282-5d63-477e-bae9-abb0fa25b96a",
        database="tracardi",
        table="profile",
        column="data_job_company_country",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="864090dc-e468-409d-ae99-38e9a54c1b92",
        database="tracardi",
        table="profile",
        column="data_job_department",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="e5b643a5-4d0b-4615-b6a1-b0b4f0ca0cb5",
        database="tracardi",
        table="profile",
        column="data_metrics_ltv",
        type="float",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a259b1a2-9bf6-4222-8da0-76a6d86aaf66",
        database="tracardi",
        table="profile",
        column="data_loyalty_codes",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a5baab99-e867-4d0f-91fd-3bc190e10dd2",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_id",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="e7dc4c68-9414-4354-b896-c8edd943cd5d",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_name",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="34c6c658-2dc7-496b-9a22-cb30df46a93d",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_issuer",
        type="string",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="ab760f80-6e32-4012-918a-774337196380",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_expires",
        type="datetime",
        default='NULL',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="73206a75-edd6-442d-9a58-cfbfcdc0da6a",
        database="tracardi",
        table="profile",
        column="data_loyalty_card_points",
        type="float",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="6fca8ab4-2471-40df-a12c-6c888a6918df",
        database="tracardi",
        table="profile",
        column="data_devices_push",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="bd1a3fb1-34aa-447a-8df6-b64c60171e8f",
        database="tracardi",
        table="profile",
        column="data_devices_other",
        type="List[str]",
        default='[]',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="be8fb25a-9439-41c8-8b0b-36ead967bc76",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_location",
        type="Tuple[float,float]",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="74e8e3a6-40cf-46d9-907f-a7e65d9b43e3",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_longitude",
        type="float",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="cfeff116-cabf-4ff4-9327-15ae3ef67602",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_latitude",
        type="float",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="dcf3d7a6-787e-45bb-8f25-2fa5abf55ec7",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_postal",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="d5419a86-fd9a-41b1-8311-0a5799e240cb",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_county",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="1057c47a-fa1c-4588-a663-9db0a0f91346",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_city",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="331790a5-b0c6-4fae-a796-72e1dc1b70eb",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_country_code",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="a1cdb1d0-c7e3-4023-83ce-8069e6b46569",
        database="tracardi",
        table="profile",
        column="data_devices_last_geo_country_name",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="13a3dffe-22d1-4d3a-886d-fb5244a5bfe9",
        database="tracardi",
        table="profile",
        column="data_contact_confirmations",
        type="List[str]",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8a9fcaee-de53-4a1d-9f4d-485e4df0a204",
        database="tracardi",
        table="profile",
        column="operation_merge",
        type="List[str]",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="39a9940b-ec54-4552-b7d2-58880af24b12",
        database="tracardi",
        table="profile",
        column="operation_segment",
        type="bool",
        default='false',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="540d0ed5-8ea0-4595-a998-5757479455d5",
        database="tracardi",
        table="profile",
        column="metadata_status",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="b27bc369-f1c3-43c6-977e-c4f01656ab77",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_tz",
        type="string",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="8e3e72e3-6060-4b53-bc90-2eeeacd039e8",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_count",
        type="integer",
        default='0',
        nullable=True
    ),
    SystemEntityTableColumn(
        id="c98a3e81-9caa-469f-ad40-27bd98d0116f",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_current",
        type="datetime",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="739f575d-fdbc-4b28-99af-2aa9ee640f3a",
        database="tracardi",
        table="profile",
        column="metadata_time_visit_last",
        type="datetime",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="fbd4f752-8deb-425a-9a35-331c9fb2b7eb",
        database="tracardi",
        table="profile",
        column="metadata_time_segmentation",
        type="datetime",
        default=None,
        nullable=True
    ),
    SystemEntityTableColumn(
        id="78c40875-cb02-4814-80dd-b662a1922c62",
        database="tracardi",
        table="profile",
        column="primary_id",
        type="string",
        default='NULL',
        nullable=True
    ),
]



# from tracardi.service.setup.mappings.objects.profile import default_profile_properties
# from uuid import uuid4
# db = {v.property.replace(".", "_"):v.id for v in default_profile_properties}
#
# for x in default_profile_table_columns:
#     print(
# f"""SystemEntityPropertyToColumn(
#     id = "{uuid4()}",
#     property_id = "{db.get(x.column)}",  # {x.column.replace("_", ".")}
#     column_id = "{x.id}",  # {x.column}
#     mode = "p"
# ),"""
#     )
#     print(
#         f"""SystemEntityPropertyToColumn(
#         id = "{uuid4()}",
#         property_id = "{db.get(x.column)}",  # {x.column.replace("_", ".")}
#         column_id = "{x.id}",  # {x.column}
#         mode = "t"
#     ),"""
#     )
