from typing import List

from tracardi.domain.system_entity_property import SystemEntityProperty

default_profile_properties: List[SystemEntityProperty] = [
    SystemEntityProperty(**{'entity':'profile', 'id':  'id', 'type': 'string', 'optional': False, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'ids', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.time.insert', 'type': 'datetime', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.time.create', 'type': 'datetime', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.time.update', 'type': 'datetime', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'operation.new', 'type': 'bool', 'optional': True, 'default': 'False'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'operation.update', 'type': 'bool', 'optional': True, 'default': 'False'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'stats.visits', 'type': 'integer', 'optional': True, 'default': '0'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'stats.views', 'type': 'integer', 'optional': False, 'default': '0'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'stats.counters', 'type': 'dict', 'optional': False, 'default': '{}'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'traits', 'type': 'dict', 'optional': True, 'default': '{}'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'segments', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'interests', 'type': 'dict', 'optional': True, 'default': '{}'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'consents', 'type': 'Dict[str, ConsentRevoke]', 'optional': True, 'default': '{}'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'active', 'type': 'bool', 'optional': False, 'default': 'True'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'aux', 'type': 'dict', 'optional': True, 'default': '{}'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.anonymous', 'type': 'bool', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.firstname', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.lastname', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.display_name', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.birthday', 'type': 'datetime', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.language.native', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.language.spoken', 'type': 'List[str]', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.gender', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.education.level', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.civil.status', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.attributes.height', 'type': 'float', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.attributes.weight', 'type': 'float', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.pii.attributes.shoe_number', 'type': 'float', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.email.main', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.email.private', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.email.business', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.phone.main', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.phone.business', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.phone.mobile', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.phone.whatsapp', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.app.whatsapp', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.app.discord', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.app.slack', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.app.twitter', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.app.telegram', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.app.wechat', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.app.viber', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.app.signal', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.address.town', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.address.county', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.address.country', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.address.postcode', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.address.street', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.address.other', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.identifier.id', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.identifier.pk', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.identifier.badge', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.identifier.passport', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.identifier.credit_card', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.identifier.token', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.identifier.coupons', 'type': 'List[str]', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.image', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.webpage', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.social.twitter', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.social.facebook', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.social.youtube', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.social.instagram', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.social.tiktok', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.social.linkedin', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.social.reddit', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.media.social.other', 'type': 'dict', 'optional': True, 'default': '{}'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.purchases', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.colors', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.sizes', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.devices', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.channels', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.payments', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.brands', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.fragrances', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.services', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.preferences.other', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.job.position', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.job.salary', 'type': 'float', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.job.type', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.job.company.name', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.job.company.size', 'type': 'int', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.job.company.segment', 'type': 'List[str]', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.job.company.country', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.job.department', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.metrics.ltv', 'type': 'float', 'optional': True, 'default': '0'}),
    # SystemEntityProperty(**{'entity':'profile', 'id':  'data.metrics.ltcosc', 'type': 'int', 'optional': True, 'default': '0'}),
    # SystemEntityProperty(**{'entity':'profile', 'id':  'data.metrics.ltcocc', 'type': 'int', 'optional': True, 'default': '0'}),
    # SystemEntityProperty(**{'entity':'profile', 'id':  'data.metrics.ltcop', 'type': 'float', 'optional': True, 'default': '0'}),
    # SystemEntityProperty(**{'entity':'profile', 'id':  'data.metrics.ltcosv', 'type': 'float', 'optional': True, 'default': '0'}),
    # SystemEntityProperty(**{'entity':'profile', 'id':  'data.metrics.ltcocv', 'type': 'float', 'optional': True, 'default': '0'}),
    # SystemEntityProperty(**{'entity':'profile', 'id':  'data.metrics.next', 'type': 'datetime', 'optional': True, 'default': 'NULL'}),
    # SystemEntityProperty(**{'entity':'profile', 'id':  'data.metrics.custom', 'type': 'dict', 'optional': True, 'default': '{}'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.loyalty.codes', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.loyalty.card.id', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.loyalty.card.name', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.loyalty.card.issuer', 'type': 'string', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.loyalty.card.expires', 'type': 'datetime', 'optional': True, 'default': 'NULL'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.loyalty.card.points', 'type': 'float', 'optional': True, 'default': '0'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.push', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.other', 'type': 'List[str]', 'optional': True, 'default': '[]'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.last.geo.location', 'type': 'Tuple[float,float]', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.last.geo.longitude', 'type': 'float', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.last.geo.latitude', 'type': 'float', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.last.geo.postal', 'type': 'string', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.last.geo.county', 'type': 'string', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.last.geo.city', 'type': 'string', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.last.geo.country.code', 'type': 'string', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.devices.last.geo.country.name', 'type': 'string', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'data.contact.confirmations', 'type': 'List[str]', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'stats.views', 'type': 'integer', 'optional': True, 'default': '0'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'stats.visits', 'type': 'integer', 'optional': True, 'default': '0'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'operation.merge', 'type': 'List[str]', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'operation.segment', 'type': 'bool', 'optional': True, 'default': "false"}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.status', 'type': 'string', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.time.visit.tz', 'type': 'string', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.time.visit.count', 'type': 'integer', 'optional': True, 'default': '0'}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.time.visit.current', 'type': 'datetime', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.time.visit.last', 'type': 'datetime', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'metadata.time.segmentation', 'type': 'datetime', 'optional': True, 'default': None}),
    SystemEntityProperty(**{'entity':'profile', 'id':  'primary_id', 'type': 'string', 'optional': True, 'default': 'NULL'})
]
